title: 西湖大学校园风景短镜头库
description: 存储和分享我的短镜头视频
baseurl: "/westlakeu_scenery" 
url: "https://xdyydx.github.io" 
cdn_username: "xdyydx" #你的GitHub用户名
cdn_repo: "westlakeu_scenery" #你的仓库名
cdn_branch: "main" #分支名
markdown: kramdown
defaults:
  - scope:
      path: ""
    values:
      layout: "default"